### TEST TELEGRAM BOT
POST http://localhost:8000/api/test-tg-bot
Content-Type: application/json
Accept: application/json

### AUTHENTICATION
POST http://localhost:8000/api/auth/authenticate
#POST https://bk-api.magiquetechnologies.tech/api/auth/authenticate
Content-Type: application/json
Accept: application/json

{
    "user_name":"bkapi@user.com",
    "password":"MTechBKApi@2050"
}

### INITIATE PAYMENTS
#POST http://localhost:8000/api/payment/initiate
POST https://bk-api.magiquetechnologies.tech/api/payment/initiate
Content-Type: application/json
Accept: application/json
#Authorization: Bearer 7|18LdQUZ3dmYouMikqtGdA8Fti91i3If7DiWXk11x73211579

{
    "amount":"20",
    "channel_name":"MOMO",
    "payer_code":"2",
    "payer_names":"Daniel Ndungo",
    "phone_number":"250795586806",
    "payer_email":"magiquepryce@gmail.com"
}


### TRANSACTION STATUS
#POST http://localhost:8000/api/transaction/status
POST https://bk-api.magiquetechnologies.tech/api/transaction/status
Content-Type: application/json
Accept: application/json
#Authorization: Bearer 7|18LdQUZ3dmYouMikqtGdA8Fti91i3If7DiWXk11x73211579

{
    "transaction_id":"11202602121611357052"
}


